/**
 * Auto-generated TypeScript types from Rust definitions
 * DO NOT EDIT - Changes will be overwritten
 * Generated by: cargo run --bin generate-types
 */

// Common Types

/**
 * API Response wrapper for all backend calls
 */
export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
}

/**
 * Error response structure
 */
export interface ErrorResponse {
  message: string;
  code?: string;
  context?: Record<string, unknown>;
}

// System Information Types

export interface OsInfo {
  platform: string;
  arch: string;
  family: string;
}

export interface MemoryInfo {
  total: number;
  available: number;
  used: number;
  buffers?: number;
  cached?: number;
  swapTotal?: number;
  swapFree?: number;
}

export interface CpuInfo {
  model: string;
  cores: number;
}

export interface DiskInfo {
  device: string;
  mountPoint: string;
  total: number;
  used: number;
  available: number;
  usagePercent: number;
}

export interface SystemInfo {
  os: OsInfo;
  memory: MemoryInfo;
  cpu: CpuInfo;
  disk: DiskInfo[];
  uptime: string;
  cwd: string;
}

// Settings Types

export interface AppSettings {
  theme: string;
  language: string;
  autoSave: boolean;
}

// File Manager Types

export interface FileEntry {
  name: string;
  path: string;
  isDir: boolean;
  size?: number;
  modified?: string;
}

// Process Types

export interface ProcessInfo {
  pid: number;
  name: string;
  cpuUsage: number;
  memoryUsage: number;
}

// Clipboard Types

export interface ClipboardContent {
  text?: string;
  html?: string;
}

// Window Management Types

export interface WindowState {
  isFocused: boolean;
  isMinimized: boolean;
  isMaximized: boolean;
}

export interface WindowAction {
  windowId: string;
  windowTitle: string;
}


// Backend API Interface
// All available backend functions with their signatures

export interface BackendAPI {
  // System Information
  getSystemInfo(): Promise<ApiResponse<SystemInfo>>;

  // Settings
  getSettings(): Promise<ApiResponse<AppSettings>>;
  updateSettings(settings: AppSettings): Promise<ApiResponse<void>>;

  // File Manager
  listDirectory(path: string): Promise<ApiResponse<FileEntry[]>>;

  // Clipboard
  getClipboard(): Promise<ApiResponse<ClipboardContent>>;
  setClipboard(text: string): Promise<ApiResponse<void>>;

  // Process Management
  listProcesses(): Promise<ApiResponse<ProcessInfo[]>>;
  killProcess(pid: number): Promise<ApiResponse<void>>;

  // Window Management
  windowFocus(action: WindowAction): Promise<ApiResponse<void>>;
  windowMinimize(action: WindowAction): Promise<ApiResponse<void>>;
  windowMaximize(action: WindowAction): Promise<ApiResponse<void>>;
  windowRestore(action: WindowAction): Promise<ApiResponse<void>>;
  windowClose(action: WindowAction): Promise<ApiResponse<void>>;
}

